---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksworkshop-eksctl
  region: ${AWS_REGION}

fargateProfiles:
  - name: fargate-productcatalog
    selectors:
      - namespace: prodcatalog-ns
        labels:
          app: prodcatalog

# https://eksctl.io/usage/eks-managed-nodegroups/
managedNodeGroups:
  - name: prodcatalog-demo-ng
    minSize: 2
    maxSize: 3
    desiredCapacity: 3
    volumeSize: 20
    labels: {role: ctrl-workers}
    tags:
      nodegroup-role: ctrl-workers
    iam:
      withAddonPolicies:
        appMesh: true
        xRay: true
        cloudWatch: true

# https://eksctl.io/usage/iamserviceaccounts/
iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: prodcatalog-sa
        namespace: prodcatalog-ns
        labels: {aws-usage: "application"}
      attachPolicyARNs:
        - "arn:aws:iam::aws:policy/AWSAppMeshEnvoyAccess"
        - "arn:aws:iam::aws:policy/AWSCloudMapDiscoverInstanceAccess"
        - "arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess"
        - "arn:aws:iam::aws:policy/CloudWatchLogsFullAccess"
        - "arn:aws:iam::aws:policy/AWSAppMeshFullAccess"
        - "arn:aws:iam::aws:policy/AWSCloudMapFullAccess"